<?xml version="1.0"?>
<!DOCTYPE mame [
<!ELEMENT mame (machine+)>
	<!ATTLIST mame build CDATA #IMPLIED>
	<!ATTLIST mame debug (yes|no) "no">
	<!ATTLIST mame mameconfig CDATA #REQUIRED>
	<!ELEMENT machine (description, year?, manufacturer?, biosset*, rom*, disk*, device_ref*, sample*, chip*, display*, sound?, input?, dipswitch*, configuration*, port*, adjuster*, driver?, feature*, device*, slot*, softwarelist*, ramoption*)>
		<!ATTLIST machine name CDATA #REQUIRED>
		<!ATTLIST machine sourcefile CDATA #IMPLIED>
		<!ATTLIST machine isbios (yes|no) "no">
		<!ATTLIST machine isdevice (yes|no) "no">
		<!ATTLIST machine ismechanical (yes|no) "no">
		<!ATTLIST machine runnable (yes|no) "yes">
		<!ATTLIST machine cloneof CDATA #IMPLIED>
		<!ATTLIST machine romof CDATA #IMPLIED>
		<!ATTLIST machine sampleof CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT biosset EMPTY>
			<!ATTLIST biosset name CDATA #REQUIRED>
			<!ATTLIST biosset description CDATA #REQUIRED>
			<!ATTLIST biosset default (yes|no) "no">
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom bios CDATA #IMPLIED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom merge CDATA #IMPLIED>
			<!ATTLIST rom region CDATA #IMPLIED>
			<!ATTLIST rom offset CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good) "good">
			<!ATTLIST rom optional (yes|no) "no">
		<!ELEMENT disk EMPTY>
			<!ATTLIST disk name CDATA #REQUIRED>
			<!ATTLIST disk sha1 CDATA #IMPLIED>
			<!ATTLIST disk merge CDATA #IMPLIED>
			<!ATTLIST disk region CDATA #IMPLIED>
			<!ATTLIST disk index CDATA #IMPLIED>
			<!ATTLIST disk writable (yes|no) "no">
			<!ATTLIST disk status (baddump|nodump|good) "good">
			<!ATTLIST disk optional (yes|no) "no">
		<!ELEMENT device_ref EMPTY>
			<!ATTLIST device_ref name CDATA #REQUIRED>
		<!ELEMENT sample EMPTY>
			<!ATTLIST sample name CDATA #REQUIRED>
		<!ELEMENT chip EMPTY>
			<!ATTLIST chip name CDATA #REQUIRED>
			<!ATTLIST chip tag CDATA #IMPLIED>
			<!ATTLIST chip type (cpu|audio) #REQUIRED>
			<!ATTLIST chip clock CDATA #IMPLIED>
		<!ELEMENT display EMPTY>
			<!ATTLIST display tag CDATA #IMPLIED>
			<!ATTLIST display type (raster|vector|lcd|svg|unknown) #REQUIRED>
			<!ATTLIST display rotate (0|90|180|270) #IMPLIED>
			<!ATTLIST display flipx (yes|no) "no">
			<!ATTLIST display width CDATA #IMPLIED>
			<!ATTLIST display height CDATA #IMPLIED>
			<!ATTLIST display refresh CDATA #REQUIRED>
			<!ATTLIST display pixclock CDATA #IMPLIED>
			<!ATTLIST display htotal CDATA #IMPLIED>
			<!ATTLIST display hbend CDATA #IMPLIED>
			<!ATTLIST display hbstart CDATA #IMPLIED>
			<!ATTLIST display vtotal CDATA #IMPLIED>
			<!ATTLIST display vbend CDATA #IMPLIED>
			<!ATTLIST display vbstart CDATA #IMPLIED>
		<!ELEMENT sound EMPTY>
			<!ATTLIST sound channels CDATA #REQUIRED>
		<!ELEMENT condition EMPTY>
			<!ATTLIST condition tag CDATA #REQUIRED>
			<!ATTLIST condition mask CDATA #REQUIRED>
			<!ATTLIST condition relation (eq|ne|gt|le|lt|ge) #REQUIRED>
			<!ATTLIST condition value CDATA #REQUIRED>
		<!ELEMENT input (control*)>
			<!ATTLIST input service (yes|no) "no">
			<!ATTLIST input tilt (yes|no) "no">
			<!ATTLIST input players CDATA #REQUIRED>
			<!ATTLIST input coins CDATA #IMPLIED>
			<!ELEMENT control EMPTY>
				<!ATTLIST control type CDATA #REQUIRED>
				<!ATTLIST control player CDATA #IMPLIED>
				<!ATTLIST control buttons CDATA #IMPLIED>
				<!ATTLIST control reqbuttons CDATA #IMPLIED>
				<!ATTLIST control minimum CDATA #IMPLIED>
				<!ATTLIST control maximum CDATA #IMPLIED>
				<!ATTLIST control sensitivity CDATA #IMPLIED>
				<!ATTLIST control keydelta CDATA #IMPLIED>
				<!ATTLIST control reverse (yes|no) "no">
				<!ATTLIST control ways CDATA #IMPLIED>
				<!ATTLIST control ways2 CDATA #IMPLIED>
				<!ATTLIST control ways3 CDATA #IMPLIED>
		<!ELEMENT dipswitch (condition?, diplocation*, dipvalue*)>
			<!ATTLIST dipswitch name CDATA #REQUIRED>
			<!ATTLIST dipswitch tag CDATA #REQUIRED>
			<!ATTLIST dipswitch mask CDATA #REQUIRED>
			<!ELEMENT diplocation EMPTY>
				<!ATTLIST diplocation name CDATA #REQUIRED>
				<!ATTLIST diplocation number CDATA #REQUIRED>
				<!ATTLIST diplocation inverted (yes|no) "no">
			<!ELEMENT dipvalue (condition?)>
				<!ATTLIST dipvalue name CDATA #REQUIRED>
				<!ATTLIST dipvalue value CDATA #REQUIRED>
				<!ATTLIST dipvalue default (yes|no) "no">
		<!ELEMENT configuration (condition?, conflocation*, confsetting*)>
			<!ATTLIST configuration name CDATA #REQUIRED>
			<!ATTLIST configuration tag CDATA #REQUIRED>
			<!ATTLIST configuration mask CDATA #REQUIRED>
			<!ELEMENT conflocation EMPTY>
				<!ATTLIST conflocation name CDATA #REQUIRED>
				<!ATTLIST conflocation number CDATA #REQUIRED>
				<!ATTLIST conflocation inverted (yes|no) "no">
			<!ELEMENT confsetting (condition?)>
				<!ATTLIST confsetting name CDATA #REQUIRED>
				<!ATTLIST confsetting value CDATA #REQUIRED>
				<!ATTLIST confsetting default (yes|no) "no">
		<!ELEMENT port (analog*)>
			<!ATTLIST port tag CDATA #REQUIRED>
			<!ELEMENT analog EMPTY>
				<!ATTLIST analog mask CDATA #REQUIRED>
		<!ELEMENT adjuster (condition?)>
			<!ATTLIST adjuster name CDATA #REQUIRED>
			<!ATTLIST adjuster default CDATA #REQUIRED>
		<!ELEMENT driver EMPTY>
			<!ATTLIST driver status (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver emulation (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver cocktail (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver savestate (supported|unsupported) #REQUIRED>
			<!ATTLIST driver requiresartwork (yes|no) "no">
			<!ATTLIST driver unofficial (yes|no) "no">
			<!ATTLIST driver nosoundhardware (yes|no) "no">
			<!ATTLIST driver incomplete (yes|no) "no">
		<!ELEMENT feature EMPTY>
			<!ATTLIST feature type (protection|timing|graphics|palette|sound|capture|camera|microphone|controls|keyboard|mouse|media|disk|printer|tape|punch|drum|rom|comms|lan|wan) #REQUIRED>
			<!ATTLIST feature status (unemulated|imperfect) #IMPLIED>
			<!ATTLIST feature overall (unemulated|imperfect) #IMPLIED>
		<!ELEMENT device (instance?, extension*)>
			<!ATTLIST device type CDATA #REQUIRED>
			<!ATTLIST device tag CDATA #IMPLIED>
			<!ATTLIST device fixed_image CDATA #IMPLIED>
			<!ATTLIST device mandatory CDATA #IMPLIED>
			<!ATTLIST device interface CDATA #IMPLIED>
			<!ELEMENT instance EMPTY>
				<!ATTLIST instance name CDATA #REQUIRED>
				<!ATTLIST instance briefname CDATA #REQUIRED>
			<!ELEMENT extension EMPTY>
				<!ATTLIST extension name CDATA #REQUIRED>
		<!ELEMENT slot (slotoption*)>
			<!ATTLIST slot name CDATA #REQUIRED>
			<!ELEMENT slotoption EMPTY>
				<!ATTLIST slotoption name CDATA #REQUIRED>
				<!ATTLIST slotoption devname CDATA #REQUIRED>
				<!ATTLIST slotoption default (yes|no) "no">
		<!ELEMENT softwarelist EMPTY>
			<!ATTLIST softwarelist tag CDATA #REQUIRED>
			<!ATTLIST softwarelist name CDATA #REQUIRED>
			<!ATTLIST softwarelist status (original|compatible) #REQUIRED>
			<!ATTLIST softwarelist filter CDATA #IMPLIED>
		<!ELEMENT ramoption (#PCDATA)>
			<!ATTLIST ramoption name CDATA #REQUIRED>
			<!ATTLIST ramoption default CDATA #IMPLIED>
]>

<mame build="0.245 (mame0245) - Arcade Database" debug="no" mameconfig="10">
	<machine name="daytona2" sourcefile="model3.cpp">
  <description>Daytona USA 2 (Japan, Revision A)</description>
  <year>1998</year>
  <manufacturer>Sega</manufacturer>
  <rom name="epr-20861a.17" size="2097152" crc="89ba8e78" sha1="7d27124b976a63fdadd16551a664b2cc8cc08e79" region="user1" offset="6"/>
  <rom name="epr-20862a.18" size="2097152" crc="e1b2ca61" sha1="a5aa3416554b9d62469af3fefa9c2bacd69b4707" region="user1" offset="4"/>
  <rom name="epr-20863a.19" size="2097152" crc="1deb4686" sha1="dd6fcc95afa36148089b766c24c53a2af4d392d4" region="user1" offset="2"/>
  <rom name="epr-20864a.20" size="2097152" crc="5250f3a8" sha1="d75b86cb320b854fcf53e1b76331f87806b9ae84" region="user1" offset="0"/>
  <rom name="mpr-20845.1" size="8388608" crc="6037712c" sha1="904beb9da47ceec4e3e68791895404cca55ef21e" region="user1" offset="800006"/>
  <rom name="mpr-20846.2" size="8388608" crc="f44c5c7a" sha1="256417b75d351cabb67629b62c8277a4c437b858" region="user1" offset="800004"/>
  <rom name="mpr-20847.3" size="8388608" crc="eda966ee" sha1="59720fefdefdd8cc909ea7ac95e0a8c3e191f2f1" region="user1" offset="800002"/>
  <rom name="mpr-20848.4" size="8388608" crc="5b6c8b7d" sha1="caf723e669b4b58d8cb5a5e9114ff9a40cfa2eea" region="user1" offset="800000"/>
  <rom name="mpr-20849.5" size="8388608" crc="50dee4af" sha1="1e07efbc9a1997aa991be5852ec89f21b0416348" region="user1" offset="2800006"/>
  <rom name="mpr-20850.6" size="8388608" crc="cb73758a" sha1="df92a494a407b2d28fec7b38c73021966bcead96" region="user1" offset="2800004"/>
  <rom name="mpr-20851.7" size="8388608" crc="6e7a64b7" sha1="ddda7c50a76e815e6e85c9cb3d32a36efe69e68d" region="user1" offset="2800002"/>
  <rom name="mpr-20852.8" size="8388608" crc="d606ad38" sha1="07902b25b2950087cef8eaec0e4680934085d19b" region="user1" offset="2800000"/>
  <rom name="mpr-20853.9" size="4194304" crc="3245ee68" sha1="f957df447bab0559076bc8a14eeaa080040acb85" region="user1" offset="4800006"/>
  <rom name="mpr-20854.10" size="4194304" crc="68d94cdf" sha1="298236225ab5d0265ec615e71d084c79932d0438" region="user1" offset="4800004"/>
  <rom name="mpr-20855.11" size="4194304" crc="f1ff0794" sha1="22782a01de0b699e7663aeb659169581830e69fd" region="user1" offset="4800002"/>
  <rom name="mpr-20856.12" size="4194304" crc="0367a242" sha1="e3bb0ad7abddd8e81e4052dae169dfa245acbfa8" region="user1" offset="4800000"/>
  <rom name="mpr-20857.13" size="4194304" crc="1eab9c62" sha1="7c5cbab2761609cdf6ab20c2e198135fa9ae1067" region="user1" offset="6800006"/>
  <rom name="mpr-20858.14" size="4194304" crc="407fbad5" sha1="594d45311d1daf00773b466c64ece4975df4dd5a" region="user1" offset="6800004"/>
  <rom name="mpr-20859.15" size="4194304" crc="e14f5c46" sha1="d80ccd2c5ea1f34280241aaa5c947397b0344820" region="user1" offset="6800002"/>
  <rom name="mpr-20860.16" size="4194304" crc="e5ce2939" sha1="7e5626cfb68402de80a05e4c3b18bdfd8bb40f85" region="user1" offset="6800000"/>
  <rom name="mpr-20870.26" size="4194304" crc="7c9e573d" sha1="0c488dcca8946b846a179dd66ca09d9eabedc21c" region="user3" offset="2"/>
  <rom name="mpr-20871.27" size="4194304" crc="47a1b789" sha1="8f817fefcfe99c27b30bb3bd9276b0a0947e5992" region="user3" offset="0"/>
  <rom name="mpr-20872.28" size="4194304" crc="2f55b423" sha1="4fa5b00715163b8f68a01627eb04dadbcbb6e89a" region="user3" offset="6"/>
  <rom name="mpr-20873.29" size="4194304" crc="c9000e48" sha1="a64a13e3116e36309ed37ec8651ef8a38b27b71f" region="user3" offset="4"/>
  <rom name="mpr-20874.30" size="4194304" crc="26a9cca2" sha1="e3b68daaef95e004217c6f7cf3c6d256d083b994" region="user3" offset="a"/>
  <rom name="mpr-20875.31" size="4194304" crc="bfefd21e" sha1="8422b16569e029fead5cfca1ab31a04179a0f4b2" region="user3" offset="8"/>
  <rom name="mpr-20876.32" size="4194304" crc="fa701b87" sha1="4134da01818cd6776a3c3396ac4f9b9e815722f2" region="user3" offset="e"/>
  <rom name="mpr-20877.33" size="4194304" crc="2cd072f1" sha1="97881da77abc1aee309de64b53a0da3d22c4112c" region="user3" offset="c"/>
  <rom name="mpr-20878.34" size="4194304" crc="e6d5bc01" sha1="d8d2e202830693ac2f32304c484276193eb550a3" region="user4" offset="2"/>
  <rom name="mpr-20879.35" size="4194304" crc="f1d727ec" sha1="aecd2096bee590e8ccab9710845e8f0675bd06b0" region="user4" offset="0"/>
  <rom name="mpr-20880.36" size="4194304" crc="8b370602" sha1="2c461ae94e0bd0fea623724b82e08238f947e26b" region="user4" offset="6"/>
  <rom name="mpr-20881.37" size="4194304" crc="397322e7" sha1="9d1c24a063e3e00ca4ee02162dc0fc6de48de2d7" region="user4" offset="4"/>
  <rom name="mpr-20882.38" size="4194304" crc="9185be51" sha1="b9f5ce29d9dda45733a649aa049124990f536fd9" region="user4" offset="a"/>
  <rom name="mpr-20883.39" size="4194304" crc="d1e39e83" sha1="8d8ccd7f23004e43ede71f73069979a3834bc010" region="user4" offset="8"/>
  <rom name="mpr-20884.40" size="4194304" crc="63c4639a" sha1="d2b47f7bb8244e0a25c15d025d1bb295101f8875" region="user4" offset="e"/>
  <rom name="mpr-20885.41" size="4194304" crc="61c292ca" sha1="a2c7e81a8a8ded8d0fd33ffea74a8d2cc8f22520" region="user4" offset="c"/>
  <rom name="epr-20865.21" size="131072" crc="b70c2699" sha1="9ec3f59eda18c03530a5ab7a54c09c1e14cb1c4d" region="audiocpu" offset="0"/>
  <rom name="mpr-20866.22" size="4194304" crc="91f40c1c" sha1="0c9bee8e9a8bb5ffb2699922204ec26b489eee84" region="samples" offset="0"/>
  <rom name="mpr-20868.24" size="4194304" crc="fa0c7ec0" sha1="e3570318b67b9e9819830ad73529a627ac2f2821" region="samples" offset="400000"/>
  <rom name="mpr-20867.23" size="4194304" crc="a579c884" sha1="ffa626381b1b2c0b963f8f0bad508c052364e657" region="samples" offset="800000"/>
  <rom name="mpr-20869.25" size="4194304" crc="1f338832" sha1="77160ea4d336aa88725b868c0035a267e92030b3" region="samples" offset="c00000"/>
  <rom name="epr-20886.ic2" size="131072" crc="65b05f98" sha1="b83a2a6e7ec3d2fcd34ce701ffa66d99f6feb86d" region="cpu2" offset="0"/>
  <rom name="mpr-20887.ic18" size="4194304" crc="a0757684" sha1="9222527d90b3f462846a4fff95af83011871c277" region="dsb" offset="0"/>
  <rom name="mpr-20888.ic20" size="4194304" crc="b495fe65" sha1="1573ced683534bb279a6dd69f6460745b728eac0" region="dsb" offset="400000"/>
  <rom name="mpr-20889.ic22" size="4194304" crc="18eec79e" sha1="341982d89952ed85c921c627c294609bf83ec44b" region="dsb" offset="800000"/>
  <rom name="mpr-20890.ic24" size="4194304" crc="aac96fa2" sha1="bc68cd48eae50d3558d3c5a0302a3930639e3019" region="dsb" offset="c00000"/>
  <rom name="epr-20985.bin" size="65536" crc="b139481d" sha1="05fca7db7c8b084c53bd157ba3e8296f1a961a99" region="drivebd" offset="0"/>
  <device_ref name="ppc603r"/>
  <device_ref name="m68000"/>
  <device_ref name="93c46_16"/>
  <device_ref name="nvram"/>
  <device_ref name="rtc72421"/>
  <device_ref name="315_5649"/>
  <device_ref name="screen"/>
  <device_ref name="palette"/>
  <device_ref name="gfxdecode"/>
  <device_ref name="speaker"/>
  <device_ref name="speaker"/>
  <device_ref name="scsp"/>
  <device_ref name="scsp"/>
  <device_ref name="segabill"/>
  <device_ref name="z80"/>
  <device_ref name="315_5338a"/>
  <device_ref name="m3comm"/>
  <device_ref name="m68000"/>
  <device_ref name="ram"/>
  <device_ref name="sega315_5881"/>
  <chip type="cpu" tag="maincpu" name="IBM PowerPC 603R" clock="166000000"/>
  <chip type="cpu" tag="audiocpu" name="Motorola MC68000" clock="11289600"/>
  <chip type="cpu" tag="billboard:billcpu" name="Zilog Z80" clock="8000000"/>
  <chip type="cpu" tag="comm_board:m3commcpu" name="Motorola MC68000" clock="10000000"/>
  <chip type="audio" tag="lspeaker" name="Speaker"/>
  <chip type="audio" tag="rspeaker" name="Speaker"/>
  <chip type="audio" tag="scsp1" name="Yamaha YMF292-F SCSP" clock="22579200"/>
  <chip type="audio" tag="scsp2" name="Yamaha YMF292-F SCSP" clock="22579200"/>
  <display tag="screen" type="raster" rotate="0" width="496" height="384" refresh="57.524160" pixclock="16000000" htotal="656" hbend="0" hbstart="496" vtotal="424" vbend="0" vbstart="384"/>
  <sound channels="2"/>
  <input players="1" coins="2" service="yes">
    <control type="paddle" buttons="8" minimum="0" maximum="255" sensitivity="30" keydelta="10"/>
    <control type="pedal" minimum="0" maximum="255" sensitivity="30" keydelta="10"/>
  </input>
  <dipswitch name="Test Winner LED P1" tag="billboard:dsw" mask="1">
    <diplocation name="DSW" number="1"/>
    <dipvalue name="Off" value="1" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Test Winner LED P2" tag="billboard:dsw" mask="2">
    <diplocation name="DSW" number="2"/>
    <dipvalue name="Off" value="2" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Test 7-Segment P1" tag="billboard:dsw" mask="4">
    <diplocation name="DSW" number="3"/>
    <dipvalue name="Off" value="4" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Test 7-Segment P2" tag="billboard:dsw" mask="8">
    <diplocation name="DSW" number="4"/>
    <dipvalue name="Off" value="8" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Unknown" tag="billboard:dsw" mask="16">
    <diplocation name="DSW" number="5"/>
    <dipvalue name="Off" value="16" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Unknown" tag="billboard:dsw" mask="32">
    <diplocation name="DSW" number="6"/>
    <dipvalue name="Off" value="32" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Demo" tag="billboard:dsw" mask="64">
    <diplocation name="DSW" number="7"/>
    <dipvalue name="Off" value="0" default="yes"/>
    <dipvalue name="On" value="64"/>
  </dipswitch>
  <dipswitch name="Testmode" tag="billboard:dsw" mask="128">
    <diplocation name="DSW" number="8"/>
    <dipvalue name="Off" value="0" default="yes"/>
    <dipvalue name="On" value="128"/>
  </dipswitch>
  <port tag=":AN0">
    <analog mask="255"/>
  </port>
  <port tag=":AN1">
    <analog mask="255"/>
  </port>
  <port tag=":AN2">
    <analog mask="255"/>
  </port>
  <port tag=":AN3"/>
  <port tag=":AN4"/>
  <port tag=":AN5"/>
  <port tag=":AN6"/>
  <port tag=":AN7"/>
  <port tag=":DSW"/>
  <port tag=":IN0"/>
  <port tag=":IN1"/>
  <port tag=":IN2"/>
  <port tag=":IN3"/>
  <port tag=":billboard:dsw"/>
  <driver status="preliminary" emulation="preliminary" savestate="unsupported"/>
  <feature type="graphics" status="imperfect"/>
  <feature type="sound" status="imperfect"/>
</machine>
	<machine name="segabill" sourcefile="src/mame/machine/segabill.cpp" isdevice="yes" runnable="no">
  <description>Sega Billboard</description>
  <rom name="epr-18022.ic2" size="65536" crc="0ca70f80" sha1="edf5ade72d9fa2f4d5f83f9f89e6cecfadd77f56" region="billcpu" offset="0"/>
  <device_ref name="z80"/>
  <device_ref name="315_5338a"/>
  <chip type="cpu" tag=":billcpu" name="Zilog Z80" clock="8000000"/>
  <dipswitch name="Test Winner LED P1" tag=":dsw" mask="1">
    <diplocation name="DSW" number="1"/>
    <dipvalue name="Off" value="1" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Test Winner LED P2" tag=":dsw" mask="2">
    <diplocation name="DSW" number="2"/>
    <dipvalue name="Off" value="2" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Test 7-Segment P1" tag=":dsw" mask="4">
    <diplocation name="DSW" number="3"/>
    <dipvalue name="Off" value="4" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Test 7-Segment P2" tag=":dsw" mask="8">
    <diplocation name="DSW" number="4"/>
    <dipvalue name="Off" value="8" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Unknown" tag=":dsw" mask="16">
    <diplocation name="DSW" number="5"/>
    <dipvalue name="Off" value="16" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Unknown" tag=":dsw" mask="32">
    <diplocation name="DSW" number="6"/>
    <dipvalue name="Off" value="32" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Demo" tag=":dsw" mask="64">
    <diplocation name="DSW" number="7"/>
    <dipvalue name="Off" value="0" default="yes"/>
    <dipvalue name="On" value="64"/>
  </dipswitch>
  <dipswitch name="Testmode" tag=":dsw" mask="128">
    <diplocation name="DSW" number="8"/>
    <dipvalue name="Off" value="0" default="yes"/>
    <dipvalue name="On" value="128"/>
  </dipswitch>
</machine>
	<machine name="dayto2pe" sourcefile="model3.cpp">
  <description>Daytona USA 2 Power Edition (Japan)</description>
  <year>1998</year>
  <manufacturer>Sega</manufacturer>
  <rom name="epr-21178.17" size="2097152" crc="230bf8ac" sha1="bc64c4f8a794ca59b5c488a34d1b5a2b67af8fec" region="user1" offset="6"/>
  <rom name="epr-21179.18" size="2097152" crc="d5ffb4d6" sha1="e1160bfcc180667463815b64e1815be38b6ef49d" region="user1" offset="4"/>
  <rom name="epr-21180.19" size="2097152" crc="6e7b98ed" sha1="67b0153dbc67c5df9231a968fd8a9714a1bb3f67" region="user1" offset="2"/>
  <rom name="epr-21181.20" size="2097152" crc="bf0007ed" sha1="4e044313e7abbd4d68c1c78ad9464688d7614590" region="user1" offset="0"/>
  <rom name="mpr-21182.1" size="4194304" crc="ba8e667f" sha1="649f273cc612b014d9b04d301da018d248a73839" region="user1" offset="800006"/>
  <rom name="mpr-21183.2" size="4194304" crc="b4b44805" sha1="8db3700207ec530ee3a83431fc891d7ab3d3bfec" region="user1" offset="800004"/>
  <rom name="mpr-21184.3" size="4194304" crc="25616403" sha1="6607734479806a8812bff4d6a697f6a024156142" region="user1" offset="800002"/>
  <rom name="mpr-21185.4" size="4194304" crc="b6d5d2a1" sha1="8e6548d65d926934c5ee3ee3669d1ce2a880bc82" region="user1" offset="800000"/>
  <rom name="mpr-21186.5" size="4194304" crc="a6128662" sha1="52514e8ad978688e812a2a7d0fb54817814f2729" region="user1" offset="2800006"/>
  <rom name="mpr-21187.6" size="4194304" crc="3bd14ee6" sha1="55d403c38439d9d489ce94bc34017ea43df27e91" region="user1" offset="2800004"/>
  <rom name="mpr-21188.7" size="4194304" crc="753fc2a5" sha1="1d4bd2b971fb0b7897109f078e260eaae437a78c" region="user1" offset="2800002"/>
  <rom name="mpr-21189.8" size="4194304" crc="cb439c45" sha1="a6326ae9cbbaa7235d7c9e45fa4dbc7267b681c9" region="user1" offset="2800000"/>
  <rom name="mpr-21190.9" size="4194304" crc="984d56eb" sha1="a04beeeadc8a11730b41ae66607777be3a7b1b5e" region="user1" offset="4800006"/>
  <rom name="mpr-21191.10" size="4194304" crc="a2bdcfe0" sha1="c72896d0338a98efe83e70284c49b966d679e7ea" region="user1" offset="4800004"/>
  <rom name="mpr-21192.11" size="4194304" crc="60cbb1fa" sha1="3b1d2da551a287efdc97e46ffeed56cf7e967bd5" region="user1" offset="4800002"/>
  <rom name="mpr-21193.12" size="4194304" crc="4638fef4" sha1="0c880119c642c96b5f88eb024575f320d099d988" region="user1" offset="4800000"/>
  <rom name="mpr-21194.13" size="4194304" crc="12c7a414" sha1="3069ce4e50a82e243fa0c794faeafd735625df5c" region="user1" offset="6800006"/>
  <rom name="mpr-21195.14" size="4194304" crc="7f39761c" sha1="e861e3c622bdc44510bd0ca7e2ef1284e4550d2e" region="user1" offset="6800004"/>
  <rom name="mpr-21196.15" size="4194304" crc="0ab46db5" sha1="8c7ab959c677e6b8f1d1bc79cd8e04299aab56aa" region="user1" offset="6800002"/>
  <rom name="mpr-21197.16" size="4194304" crc="04015247" sha1="a8b3d1f9572367e1c84475035ae0c6bb7726f01d" region="user1" offset="6800000"/>
  <rom name="mpr-21198.26" size="4194304" crc="42ec9ed4" sha1="bdc73050a5e51032478df77a02f7cd4b4ed9d337" region="user3" offset="2"/>
  <rom name="mpr-21199.27" size="4194304" crc="fa28088c" sha1="851f4fc5baa596f78bed21b0fe0e756865c19a9b" region="user3" offset="0"/>
  <rom name="mpr-21200.28" size="4194304" crc="fbb5aa1d" sha1="04b25e8fb8783e785fd471ffcf8330ca9f2e3ae7" region="user3" offset="6"/>
  <rom name="mpr-21201.29" size="4194304" crc="e6b13469" sha1="4968ab49aba86d6adcfb6200a5a02a410bbbd98c" region="user3" offset="4"/>
  <rom name="mpr-21202.30" size="4194304" crc="e6b4c2be" sha1="d3209101793f44d4ece327f24cd3a8a52bfc8298" region="user3" offset="a"/>
  <rom name="mpr-21203.31" size="4194304" crc="32d08d33" sha1="dd9a3ac5a8306b861e32bbbfad2d4c5a7790c45d" region="user3" offset="8"/>
  <rom name="mpr-21204.32" size="4194304" crc="ef18fe0a" sha1="81c8c87537eef6266b5ab464ba84cd12594e64bd" region="user3" offset="e"/>
  <rom name="mpr-21205.33" size="4194304" crc="4687bea6" sha1="6633ad8ea96f8b3a89f49dbe52f92906be504ba1" region="user3" offset="c"/>
  <rom name="mpr-21206.34" size="4194304" crc="ec2d6884" sha1="8ec53005830902ebeb4f0ee36c5b2b73c2df5ebd" region="user4" offset="2"/>
  <rom name="mpr-21207.35" size="4194304" crc="eeaa510b" sha1="5f1b9e1d09f4866289ac4ad718cb90329a93353f" region="user4" offset="0"/>
  <rom name="mpr-21208.36" size="4194304" crc="b222fef0" sha1="88cf7ce17feef2da34a86217cced98a32051b22b" region="user4" offset="6"/>
  <rom name="mpr-21209.37" size="4194304" crc="170a28ce" sha1="ca0043d42e02f5913e4eb92686586704724a3e5e" region="user4" offset="4"/>
  <rom name="mpr-21210.38" size="4194304" crc="460cefe0" sha1="820f3780e89173134792c62cc43f7c629bd555dd" region="user4" offset="a"/>
  <rom name="mpr-21211.39" size="4194304" crc="c84759ce" sha1="9b2de7fa26684457a61a2eeb0a69bd28125dd118" region="user4" offset="8"/>
  <rom name="mpr-21212.40" size="4194304" crc="6f8a75e0" sha1="3b6cb238c29a6778be354882cd27b371ce96d332" region="user4" offset="e"/>
  <rom name="mpr-21213.41" size="4194304" crc="de75bec6" sha1="f0d6f143ad227b221bf7f7c3d1b2edaa28ad4813" region="user4" offset="c"/>
  <rom name="epr-21325.21" size="131072" crc="004ad6ad" sha1="3cedc58aaf40539325870c99ecedf51f161f4f4c" region="audiocpu" offset="0"/>
  <rom name="mpr-21285.22" size="4194304" crc="7cdca6ac" sha1="fda23365d5c40f4f9e810def914cd70418e5662e" region="samples" offset="0"/>
  <rom name="mpr-21287.24" size="4194304" crc="06b66f17" sha1="a7ce8f49d2db804429cedb5db53de8762b05845a" region="samples" offset="400000"/>
  <rom name="mpr-21286.23" size="4194304" crc="749dfef0" sha1="43032b465f426188a6d718f22a11c6d9a79f7577" region="samples" offset="800000"/>
  <rom name="mpr-21288.25" size="4194304" crc="14bee38e" sha1="68300bf663ec3f597c73e7a39ca7057cf51a7a47" region="samples" offset="c00000"/>
  <rom name="epr-20886.ic2" size="131072" crc="65b05f98" sha1="b83a2a6e7ec3d2fcd34ce701ffa66d99f6feb86d" region="cpu2" offset="0"/>
  <rom name="mpr-20887.ic18" size="4194304" crc="a0757684" sha1="9222527d90b3f462846a4fff95af83011871c277" region="dsb" offset="0"/>
  <rom name="mpr-20888.ic20" size="4194304" crc="b495fe65" sha1="1573ced683534bb279a6dd69f6460745b728eac0" region="dsb" offset="400000"/>
  <rom name="mpr-20889.ic22" size="4194304" crc="18eec79e" sha1="341982d89952ed85c921c627c294609bf83ec44b" region="dsb" offset="800000"/>
  <rom name="mpr-20890.ic24" size="4194304" crc="aac96fa2" sha1="bc68cd48eae50d3558d3c5a0302a3930639e3019" region="dsb" offset="c00000"/>
  <rom name="epr-20985.bin" size="65536" crc="b139481d" sha1="05fca7db7c8b084c53bd157ba3e8296f1a961a99" region="drivebd" offset="0"/>
  <device_ref name="ppc603r"/>
  <device_ref name="m68000"/>
  <device_ref name="93c46_16"/>
  <device_ref name="nvram"/>
  <device_ref name="rtc72421"/>
  <device_ref name="315_5649"/>
  <device_ref name="screen"/>
  <device_ref name="palette"/>
  <device_ref name="gfxdecode"/>
  <device_ref name="speaker"/>
  <device_ref name="speaker"/>
  <device_ref name="scsp"/>
  <device_ref name="scsp"/>
  <device_ref name="segabill"/>
  <device_ref name="z80"/>
  <device_ref name="315_5338a"/>
  <device_ref name="m3comm"/>
  <device_ref name="m68000"/>
  <device_ref name="ram"/>
  <device_ref name="sega315_5881"/>
  <chip type="cpu" tag="maincpu" name="IBM PowerPC 603R" clock="166000000"/>
  <chip type="cpu" tag="audiocpu" name="Motorola MC68000" clock="11289600"/>
  <chip type="cpu" tag="billboard:billcpu" name="Zilog Z80" clock="8000000"/>
  <chip type="cpu" tag="comm_board:m3commcpu" name="Motorola MC68000" clock="10000000"/>
  <chip type="audio" tag="lspeaker" name="Speaker"/>
  <chip type="audio" tag="rspeaker" name="Speaker"/>
  <chip type="audio" tag="scsp1" name="Yamaha YMF292-F SCSP" clock="22579200"/>
  <chip type="audio" tag="scsp2" name="Yamaha YMF292-F SCSP" clock="22579200"/>
  <display tag="screen" type="raster" rotate="0" width="496" height="384" refresh="57.524160" pixclock="16000000" htotal="656" hbend="0" hbstart="496" vtotal="424" vbend="0" vbstart="384"/>
  <sound channels="2"/>
  <input players="1" coins="2" service="yes">
    <control type="paddle" buttons="8" minimum="0" maximum="255" sensitivity="30" keydelta="10"/>
    <control type="pedal" minimum="0" maximum="255" sensitivity="30" keydelta="10"/>
  </input>
  <dipswitch name="Test Winner LED P1" tag="billboard:dsw" mask="1">
    <diplocation name="DSW" number="1"/>
    <dipvalue name="Off" value="1" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Test Winner LED P2" tag="billboard:dsw" mask="2">
    <diplocation name="DSW" number="2"/>
    <dipvalue name="Off" value="2" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Test 7-Segment P1" tag="billboard:dsw" mask="4">
    <diplocation name="DSW" number="3"/>
    <dipvalue name="Off" value="4" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Test 7-Segment P2" tag="billboard:dsw" mask="8">
    <diplocation name="DSW" number="4"/>
    <dipvalue name="Off" value="8" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Unknown" tag="billboard:dsw" mask="16">
    <diplocation name="DSW" number="5"/>
    <dipvalue name="Off" value="16" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Unknown" tag="billboard:dsw" mask="32">
    <diplocation name="DSW" number="6"/>
    <dipvalue name="Off" value="32" default="yes"/>
    <dipvalue name="On" value="0"/>
  </dipswitch>
  <dipswitch name="Demo" tag="billboard:dsw" mask="64">
    <diplocation name="DSW" number="7"/>
    <dipvalue name="Off" value="0" default="yes"/>
    <dipvalue name="On" value="64"/>
  </dipswitch>
  <dipswitch name="Testmode" tag="billboard:dsw" mask="128">
    <diplocation name="DSW" number="8"/>
    <dipvalue name="Off" value="0" default="yes"/>
    <dipvalue name="On" value="128"/>
  </dipswitch>
  <port tag=":AN0">
    <analog mask="255"/>
  </port>
  <port tag=":AN1">
    <analog mask="255"/>
  </port>
  <port tag=":AN2">
    <analog mask="255"/>
  </port>
  <port tag=":AN3"/>
  <port tag=":AN4"/>
  <port tag=":AN5"/>
  <port tag=":AN6"/>
  <port tag=":AN7"/>
  <port tag=":DSW"/>
  <port tag=":IN0"/>
  <port tag=":IN1"/>